using System.Collections;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using Draco.Application.Interfaces;
using Draco.Application.Models;
using Draco.Domain.Entities;
using Draco.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace Draco.Infrastructure.Services;

public sealed class TerraformResourceActionService : IResourceActionService
{
    private const string AzureManagementScope = "https://management.azure.com/user_impersonation offline_access openid profile email";

    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true
    };

    private static readonly UTF8Encoding Utf8WithoutBom = new(false);

    private readonly DracoDbContext _dbContext;
    private readonly IConfiguration _configuration;
    private readonly ILogger<TerraformResourceActionService> _logger;

    public TerraformResourceActionService(
        DracoDbContext dbContext,
        IConfiguration configuration,
        ILogger<TerraformResourceActionService> logger)
    {
        _dbContext = dbContext;
        _configuration = configuration;
        _logger = logger;
    }

    public Task<IReadOnlyList<ResourceActionDefinition>> GetSupportedActionsAsync(
        CloudResource resource,
        CancellationToken cancellationToken = default)
    {
        var definitions = ResolveSpecs(resource)
            .Select(spec => new ResourceActionDefinition
            {
                Action = spec.Action,
                Label = spec.Label,
                Description = spec.Description,
                IsDestructive = spec.IsDestructive,
                Provider = resource.Provider,
                ResourceType = resource.Type,
                ExecutionMode = "Terraform"
            })
            .ToList();

        return Task.FromResult<IReadOnlyList<ResourceActionDefinition>>(definitions);
    }

    public async Task<ResourceActionExecutionResult> ExecuteAsync(
        UserAccount user,
        CloudConnection connection,
        CloudResource resource,
        string action,
        CancellationToken cancellationToken = default)
    {
        if (!string.Equals(resource.Provider, "Azure", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException("Terraform-backed resource actions currently support Azure resources only.");
        }

        var spec = ResolveSpecs(resource)
            .FirstOrDefault(candidate => string.Equals(candidate.Action, action, StringComparison.OrdinalIgnoreCase));

        if (spec is null)
        {
            throw new InvalidOperationException($"Action '{action}' is not supported for resource type '{resource.Type}'.");
        }

        var accessToken = await EnsureAzureAccessTokenAsync(connection, cancellationToken);
        var requestUri = BuildRequestUri(resource.Id, spec);
        var startedAt = DateTimeOffset.UtcNow;

        var audit = new RemediationAudit
        {
            ResourceId = resource.Id,
            ActionType = $"Terraform:{spec.Action}",
            Status = "InProgress",
            Description = spec.Description,
            AIReasoning = "Terraform-backed resource action generated by Draco.",
            PreviousState = JsonSerializer.Serialize(new
            {
                resource.Id,
                resource.Name,
                resource.Type,
                resource.Provider,
                resource.SubscriptionId,
                resource.ResourceGroupName,
                action = spec.Action,
                requestUri
            }, JsonOptions),
            ExecutedBy = user.Id.ToString()
        };

        _dbContext.RemediationAudits.Add(audit);
        await _dbContext.SaveChangesAsync(cancellationToken);

        var workspacePath = Path.Combine(
            Path.GetTempPath(),
            "draco-terraform-actions",
            audit.Id.ToString("N"));

        Directory.CreateDirectory(workspacePath);

        var scriptPath = Path.Combine(workspacePath, "execute_action.sh");
        var mainTfPath = Path.Combine(workspacePath, "main.tf");
        var responsePath = Path.Combine(workspacePath, "response.json");
        var statusPath = Path.Combine(workspacePath, "status.txt");
        var headersPath = Path.Combine(workspacePath, "headers.txt");

        var terraformConfiguration = BuildTerraformConfiguration();
        await File.WriteAllTextAsync(mainTfPath, terraformConfiguration, Utf8WithoutBom, cancellationToken);
        await File.WriteAllTextAsync(scriptPath, BuildExecutionScript(), Utf8WithoutBom, cancellationToken);

        var chmod = Process.Start(new ProcessStartInfo
        {
            FileName = "/bin/chmod",
            Arguments = $"+x \"{scriptPath}\"",
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        });

        if (chmod is not null)
        {
            await chmod.WaitForExitAsync(cancellationToken);
        }

        var terraformEnvironment = new Dictionary<string, string?>
        {
            ["access_token"] = accessToken,
            ["request_uri"] = requestUri,
            ["request_method"] = spec.HttpMethod,
            ["response_file"] = responsePath,
            ["status_file"] = statusPath,
            ["headers_file"] = headersPath,
            ["body_file"] = string.Empty
        };

        try
        {
            var initResult = await RunTerraformCommandAsync(
                "init -input=false -no-color",
                workspacePath,
                terraformEnvironment,
                cancellationToken);

            var applyResult = await RunTerraformCommandAsync(
                "apply -auto-approve -input=false -no-color",
                workspacePath,
                terraformEnvironment,
                cancellationToken);

            var responseBody = File.Exists(responsePath)
                ? await File.ReadAllTextAsync(responsePath, cancellationToken)
                : string.Empty;
            int? responseStatusCode = File.Exists(statusPath) &&
                                      int.TryParse(await File.ReadAllTextAsync(statusPath, cancellationToken), out var parsedStatus)
                ? parsedStatus
                : null;
            var responseHeaders = File.Exists(headersPath)
                ? await File.ReadAllTextAsync(headersPath, cancellationToken)
                : string.Empty;
            var pollingResult = responseStatusCode == (int)HttpStatusCode.Accepted
                ? await WaitForAzureLongRunningOperationAsync(accessToken, responseHeaders, cancellationToken)
                : null;

            var finalResponseStatusCode = pollingResult?.ResponseStatusCode ?? responseStatusCode;
            var finalResponseBody = pollingResult?.ResponseBody ?? responseBody;
            var finalOperationState = pollingResult?.OperationState;

            if (string.Equals(finalOperationState, "Failed", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(finalOperationState, "Canceled", StringComparison.OrdinalIgnoreCase))
            {
                throw new InvalidOperationException(
                    string.IsNullOrWhiteSpace(finalResponseBody)
                        ? $"Azure long-running operation ended with status '{finalOperationState}'."
                        : $"Azure long-running operation ended with status '{finalOperationState}': {finalResponseBody}");
            }

            audit.Status = string.Equals(finalOperationState, "InProgress", StringComparison.OrdinalIgnoreCase)
                ? "InProgress"
                : "Succeeded";
            audit.CompletedAt = string.Equals(audit.Status, "InProgress", StringComparison.OrdinalIgnoreCase)
                ? null
                : DateTimeOffset.UtcNow;
            audit.NewState = JsonSerializer.Serialize(new
            {
                workspacePath,
                requestUri,
                responseStatusCode = finalResponseStatusCode,
                responseBody = finalResponseBody,
                responseHeaders,
                pollUri = pollingResult?.PollUri,
                operationState = finalOperationState,
                timedOut = pollingResult?.TimedOut ?? false,
                terraform = new
                {
                    init = initResult.StandardOutput,
                    apply = applyResult.StandardOutput
                }
            }, JsonOptions);

            await _dbContext.SaveChangesAsync(cancellationToken);

            return new ResourceActionExecutionResult
            {
                AuditId = audit.Id,
                Action = spec.Action,
                Status = audit.Status,
                WorkspacePath = workspacePath,
                TerraformConfiguration = terraformConfiguration,
                Output = BuildCombinedOutput(initResult.StandardOutput, applyResult.StandardOutput, finalOperationState, pollingResult?.PollUri),
                ErrorOutput = $"{initResult.StandardError}\n{applyResult.StandardError}".Trim(),
                ResponseBody = string.IsNullOrWhiteSpace(finalResponseBody) ? null : finalResponseBody,
                ResponseStatusCode = finalResponseStatusCode,
                StartedAt = startedAt,
                CompletedAt = audit.CompletedAt
            };
        }
        catch (Exception ex)
        {
            audit.Status = "Failed";
            audit.CompletedAt = DateTimeOffset.UtcNow;
            audit.ErrorMessage = ex.Message;
            audit.NewState = JsonSerializer.Serialize(new
            {
                workspacePath,
                requestUri,
                error = ex.Message
            }, JsonOptions);

            await _dbContext.SaveChangesAsync(cancellationToken);
            throw;
        }
    }

    private IReadOnlyList<ActionSpec> ResolveSpecs(CloudResource resource)
    {
        if (!string.Equals(resource.Provider, "Azure", StringComparison.OrdinalIgnoreCase))
        {
            return [];
        }

        var normalizedType = resource.Type.Trim().ToLowerInvariant();
        if (!_azureApiVersions.TryGetValue(normalizedType, out var apiVersion))
        {
            return [];
        }

        var specs = new List<ActionSpec>();

        if (_azurePauseActionTypes.TryGetValue(normalizedType, out var pauseActionPath))
        {
            specs.Add(new ActionSpec("pause", "Pause", "Pause or stop this resource using a Terraform-generated Azure REST action.", false, "POST", apiVersion, pauseActionPath));
        }

        if (_azureResumeActionTypes.TryGetValue(normalizedType, out var resumeActionPath))
        {
            specs.Add(new ActionSpec("resume", "Resume", "Resume or start this resource using a Terraform-generated Azure REST action.", false, "POST", apiVersion, resumeActionPath));
        }

        if (_azureRestartActionTypes.TryGetValue(normalizedType, out var restartActionPath))
        {
            specs.Add(new ActionSpec("restart", "Restart", "Restart this resource using a Terraform-generated Azure REST action.", false, "POST", apiVersion, restartActionPath));
        }

        specs.Add(new ActionSpec("delete", "Delete", "Delete this resource using a Terraform-generated Azure REST action.", true, "DELETE", apiVersion, string.Empty));

        return specs;
    }

    private static string BuildRequestUri(string resourceId, ActionSpec spec)
    {
        var normalizedId = resourceId.StartsWith("/", StringComparison.Ordinal)
            ? resourceId
            : $"/{resourceId}";
        var actionSuffix = string.IsNullOrWhiteSpace(spec.ActionPath)
            ? string.Empty
            : $"/{spec.ActionPath.TrimStart('/')}";

        return $"https://management.azure.com{normalizedId}{actionSuffix}?api-version={Uri.EscapeDataString(spec.ApiVersion)}";
    }

    private async Task<string> EnsureAzureAccessTokenAsync(CloudConnection connection, CancellationToken cancellationToken)
    {
        var expiresSoon = connection.TokenExpiresAt.HasValue &&
            connection.TokenExpiresAt.Value <= DateTimeOffset.UtcNow.AddMinutes(5);

        if (!string.IsNullOrWhiteSpace(connection.AccessToken) && !expiresSoon)
        {
            return connection.AccessToken;
        }

        if (string.IsNullOrWhiteSpace(connection.RefreshToken))
        {
            if (!string.IsNullOrWhiteSpace(connection.AccessToken))
            {
                return connection.AccessToken;
            }

            throw new InvalidOperationException("Azure connection requires re-authentication before Terraform actions can run.");
        }

        using var client = new HttpClient();
        var response = await ExchangeAzureTokenAsync(
            client,
            new Dictionary<string, string>
            {
                ["grant_type"] = "refresh_token",
                ["refresh_token"] = connection.RefreshToken,
                ["scope"] = AzureManagementScope
            },
            cancellationToken);

        connection.AccessToken = response.access_token;
        connection.RefreshToken = string.IsNullOrWhiteSpace(response.refresh_token)
            ? connection.RefreshToken
            : response.refresh_token;
        connection.TokenExpiresAt = DateTimeOffset.UtcNow.AddSeconds(response.expires_in);

        await _dbContext.SaveChangesAsync(cancellationToken);
        return connection.AccessToken;
    }

    private async Task<AzureTokenResponse> ExchangeAzureTokenAsync(
        HttpClient client,
        IReadOnlyDictionary<string, string> grantValues,
        CancellationToken cancellationToken)
    {
        var clientId = _configuration["AZURE_CLIENT_ID"];
        var clientSecret = _configuration["AZURE_CLIENT_SECRET"];
        var tenantId = string.IsNullOrWhiteSpace(_configuration["AZURE_TENANT_ID"])
            ? "organizations"
            : _configuration["AZURE_TENANT_ID"]!.Trim();

        if (string.IsNullOrWhiteSpace(clientId) || string.IsNullOrWhiteSpace(clientSecret))
        {
            throw new InvalidOperationException("Azure OAuth is not configured. AZURE_CLIENT_ID and AZURE_CLIENT_SECRET are required.");
        }

        var payload = new Dictionary<string, string>(grantValues)
        {
            ["client_id"] = clientId,
            ["client_secret"] = clientSecret
        };

        using var request = new HttpRequestMessage(HttpMethod.Post, $"https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token")
        {
            Content = new FormUrlEncodedContent(payload)
        };

        request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        using var response = await client.SendAsync(request, cancellationToken);
        if (!response.IsSuccessStatusCode)
        {
            var body = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new InvalidOperationException($"Azure access token refresh failed: {(int)response.StatusCode} {body}");
        }

        var tokenResponse = await response.Content.ReadFromJsonAsync<AzureTokenResponse>(cancellationToken: cancellationToken);
        if (tokenResponse is null || string.IsNullOrWhiteSpace(tokenResponse.access_token))
        {
            throw new InvalidOperationException("Azure token refresh returned an invalid payload.");
        }

        return tokenResponse;
    }

    private async Task<TerraformCommandResult> RunTerraformCommandAsync(
        string arguments,
        string workingDirectory,
        IReadOnlyDictionary<string, string?> terraformVariables,
        CancellationToken cancellationToken)
    {
        using var process = new Process();
        process.StartInfo = new ProcessStartInfo
        {
            FileName = "terraform",
            Arguments = arguments,
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        foreach (DictionaryEntry entry in Environment.GetEnvironmentVariables())
        {
            process.StartInfo.Environment[entry.Key!.ToString()!] = entry.Value?.ToString() ?? string.Empty;
        }

        foreach (var variable in terraformVariables)
        {
            process.StartInfo.Environment[$"TF_VAR_{variable.Key.TrimStart('_')}"] = variable.Value ?? string.Empty;
        }

        var stdout = new StringBuilder();
        var stderr = new StringBuilder();

        process.OutputDataReceived += (_, args) =>
        {
            if (args.Data is not null)
            {
                stdout.AppendLine(args.Data);
            }
        };

        process.ErrorDataReceived += (_, args) =>
        {
            if (args.Data is not null)
            {
                stderr.AppendLine(args.Data);
            }
        };

        if (!process.Start())
        {
            throw new InvalidOperationException("Failed to start terraform.");
        }

        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        await process.WaitForExitAsync(cancellationToken);

        var result = new TerraformCommandResult(stdout.ToString().Trim(), stderr.ToString().Trim(), process.ExitCode);
        if (result.ExitCode != 0)
        {
            throw new InvalidOperationException(string.IsNullOrWhiteSpace(result.StandardError)
                ? $"Terraform command failed: terraform {arguments}"
                : result.StandardError);
        }

        return result;
    }

    private async Task<AzureLongRunningOperationResult?> WaitForAzureLongRunningOperationAsync(
        string accessToken,
        string responseHeaders,
        CancellationToken cancellationToken)
    {
        var headers = ParseHeaderBlock(responseHeaders);
        var pollUri = ResolveAzurePollUri(headers);
        if (string.IsNullOrWhiteSpace(pollUri))
        {
            return null;
        }

        using var client = new HttpClient();
        var retryDelay = ParseRetryAfterSeconds(headers) ?? 5;

        for (var attempt = 0; attempt < 60; attempt++)
        {
            if (attempt > 0 || retryDelay > 0)
            {
                await Task.Delay(TimeSpan.FromSeconds(retryDelay), cancellationToken);
            }

            using var request = new HttpRequestMessage(HttpMethod.Get, pollUri);
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
            request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

            using var response = await client.SendAsync(request, cancellationToken);
            var body = await response.Content.ReadAsStringAsync(cancellationToken);
            var operationState = DetermineAzureOperationState(response.StatusCode, body);

            retryDelay = ParseRetryAfterSeconds(response.Headers) ?? retryDelay;

            if (string.Equals(operationState, "Succeeded", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(operationState, "Failed", StringComparison.OrdinalIgnoreCase) ||
                string.Equals(operationState, "Canceled", StringComparison.OrdinalIgnoreCase))
            {
                return new AzureLongRunningOperationResult(operationState, (int)response.StatusCode, body, pollUri, false);
            }
        }

        return new AzureLongRunningOperationResult("InProgress", (int)HttpStatusCode.Accepted, null, pollUri, true);
    }

    private static string BuildCombinedOutput(
        string initOutput,
        string applyOutput,
        string? finalOperationState,
        string? pollUri)
    {
        var builder = new StringBuilder();

        if (!string.IsNullOrWhiteSpace(initOutput))
        {
            builder.AppendLine(initOutput.Trim());
        }

        if (!string.IsNullOrWhiteSpace(applyOutput))
        {
            if (builder.Length > 0)
            {
                builder.AppendLine();
            }

            builder.AppendLine(applyOutput.Trim());
        }

        if (!string.IsNullOrWhiteSpace(finalOperationState))
        {
            if (builder.Length > 0)
            {
                builder.AppendLine();
            }

            builder.Append("Azure operation status: ").Append(finalOperationState);

            if (!string.IsNullOrWhiteSpace(pollUri))
            {
                builder.AppendLine().Append("Polled: ").Append(pollUri);
            }
        }

        return builder.ToString().Trim();
    }

    private static Dictionary<string, string> ParseHeaderBlock(string? rawHeaders)
    {
        var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (string.IsNullOrWhiteSpace(rawHeaders))
        {
            return result;
        }

        var blocks = rawHeaders
            .Split(["\r\n\r\n", "\n\n"], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

        var lastBlock = blocks.LastOrDefault();
        if (string.IsNullOrWhiteSpace(lastBlock))
        {
            return result;
        }

        foreach (var line in lastBlock.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var separatorIndex = line.IndexOf(':');
            if (separatorIndex <= 0)
            {
                continue;
            }

            var name = line[..separatorIndex].Trim();
            var value = line[(separatorIndex + 1)..].Trim();
            if (!string.IsNullOrWhiteSpace(name))
            {
                result[name] = value;
            }
        }

        return result;
    }

    private static string? ResolveAzurePollUri(IReadOnlyDictionary<string, string> headers)
    {
        if (headers.TryGetValue("Azure-AsyncOperation", out var asyncOperationUri) && !string.IsNullOrWhiteSpace(asyncOperationUri))
        {
            return asyncOperationUri;
        }

        if (headers.TryGetValue("Operation-Location", out var operationLocation) && !string.IsNullOrWhiteSpace(operationLocation))
        {
            return operationLocation;
        }

        if (headers.TryGetValue("Location", out var location) && !string.IsNullOrWhiteSpace(location))
        {
            return location;
        }

        return null;
    }

    private static int? ParseRetryAfterSeconds(IReadOnlyDictionary<string, string> headers)
    {
        return headers.TryGetValue("Retry-After", out var retryAfterValue) &&
               int.TryParse(retryAfterValue, out var retryAfterSeconds) &&
               retryAfterSeconds > 0
            ? retryAfterSeconds
            : null;
    }

    private static int? ParseRetryAfterSeconds(HttpResponseHeaders headers)
    {
        if (headers.TryGetValues("Retry-After", out var values))
        {
            var value = values.FirstOrDefault();
            if (int.TryParse(value, out var retryAfterSeconds) && retryAfterSeconds > 0)
            {
                return retryAfterSeconds;
            }
        }

        return null;
    }

    private static string DetermineAzureOperationState(HttpStatusCode statusCode, string? responseBody)
    {
        if (statusCode == HttpStatusCode.Accepted)
        {
            return "InProgress";
        }

        if (statusCode == HttpStatusCode.NoContent)
        {
            return "Succeeded";
        }

        if (!string.IsNullOrWhiteSpace(responseBody))
        {
            try
            {
                using var document = JsonDocument.Parse(responseBody);
                if (TryReadJsonString(document.RootElement, out var directStatus, "status") ||
                    TryReadJsonString(document.RootElement, out directStatus, "properties", "provisioningState") ||
                    TryReadJsonString(document.RootElement, out directStatus, "provisioningState") ||
                    TryReadJsonString(document.RootElement, out directStatus, "properties", "status"))
                {
                    return NormalizeAzureOperationState(directStatus);
                }
            }
            catch (JsonException)
            {
            }
        }

        return statusCode is >= HttpStatusCode.OK and < HttpStatusCode.MultipleChoices
            ? "Succeeded"
            : "Failed";
    }

    private static bool TryReadJsonString(JsonElement element, out string value, params string[] path)
    {
        value = string.Empty;
        var current = element;

        foreach (var segment in path)
        {
            if (current.ValueKind != JsonValueKind.Object || !current.TryGetProperty(segment, out current))
            {
                return false;
            }
        }

        if (current.ValueKind != JsonValueKind.String)
        {
            return false;
        }

        value = current.GetString() ?? string.Empty;
        return !string.IsNullOrWhiteSpace(value);
    }

    private static string NormalizeAzureOperationState(string state)
    {
        return state.Trim().ToLowerInvariant() switch
        {
            "succeeded" => "Succeeded",
            "failed" => "Failed",
            "canceled" => "Canceled",
            "cancelled" => "Canceled",
            "inprogress" => "InProgress",
            "running" => "InProgress",
            "accepted" => "InProgress",
            _ => state
        };
    }

    private static string BuildTerraformConfiguration() =>
        """
        terraform {
          required_version = ">= 1.5.0"
        }

        variable "access_token" {
          type      = string
          sensitive = true
        }

        variable "request_uri" {
          type = string
        }

        variable "request_method" {
          type = string
        }

        variable "response_file" {
          type = string
        }

        variable "status_file" {
          type = string
        }

        variable "headers_file" {
          type = string
        }

        variable "body_file" {
          type    = string
          default = ""
        }

        resource "terraform_data" "resource_action" {
          input = {
            request_uri    = var.request_uri
            request_method = var.request_method
            response_file  = var.response_file
            status_file    = var.status_file
            headers_file   = var.headers_file
            body_file      = var.body_file
          }

          provisioner "local-exec" {
            command     = "${path.module}/execute_action.sh"
            interpreter = ["/bin/bash", "-c"]
            environment = {
              DRACO_ACCESS_TOKEN  = var.access_token
              DRACO_REQUEST_URI   = var.request_uri
              DRACO_REQUEST_METHOD = var.request_method
              DRACO_RESPONSE_FILE = var.response_file
              DRACO_STATUS_FILE   = var.status_file
              DRACO_HEADERS_FILE  = var.headers_file
              DRACO_BODY_FILE     = var.body_file
            }
          }
        }
        """;

    private static string BuildExecutionScript() =>
        """
        #!/usr/bin/env bash
        set -euo pipefail

        : "${DRACO_ACCESS_TOKEN:?}"
        : "${DRACO_REQUEST_URI:?}"
        : "${DRACO_REQUEST_METHOD:?}"
        : "${DRACO_RESPONSE_FILE:?}"
        : "${DRACO_STATUS_FILE:?}"
        : "${DRACO_HEADERS_FILE:?}"

        body_file="${DRACO_BODY_FILE:-}"

        if [[ -n "$body_file" && -f "$body_file" ]]; then
          status_code=$(curl -sS -D "$DRACO_HEADERS_FILE" -o "$DRACO_RESPONSE_FILE" -w "%{http_code}" \
            -X "$DRACO_REQUEST_METHOD" "$DRACO_REQUEST_URI" \
            -H "Authorization: Bearer $DRACO_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            --data @"$body_file")
        elif [[ "$DRACO_REQUEST_METHOD" == "POST" ]]; then
          status_code=$(curl -sS -D "$DRACO_HEADERS_FILE" -o "$DRACO_RESPONSE_FILE" -w "%{http_code}" \
            -X "$DRACO_REQUEST_METHOD" "$DRACO_REQUEST_URI" \
            -H "Authorization: Bearer $DRACO_ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            --data '')
        else
          status_code=$(curl -sS -D "$DRACO_HEADERS_FILE" -o "$DRACO_RESPONSE_FILE" -w "%{http_code}" \
            -X "$DRACO_REQUEST_METHOD" "$DRACO_REQUEST_URI" \
            -H "Authorization: Bearer $DRACO_ACCESS_TOKEN" \
            -H "Content-Type: application/json")
        fi

        echo "$status_code" > "$DRACO_STATUS_FILE"

        if [[ ! "$status_code" =~ ^20[0-9]$ ]]; then
          cat "$DRACO_RESPONSE_FILE" >&2 || true
          exit 1
        fi
        """;

    private static readonly Dictionary<string, string> _azureApiVersions = new(StringComparer.OrdinalIgnoreCase)
    {
        ["microsoft.dbformysql/flexibleservers"] = "2023-12-30",
        ["microsoft.containerinstance/containergroups"] = "2025-09-01",
        ["microsoft.web/sites"] = "2025-03-01",
        ["microsoft.web/staticsites"] = "2025-03-01",
        ["microsoft.storage/storageaccounts"] = "2024-01-01",
        ["microsoft.operationalinsights/workspaces"] = "2023-09-01",
        ["microsoft.documentdb/databaseaccounts"] = "2024-11-15",
        ["microsoft.kusto/clusters"] = "2024-04-13",
        ["microsoft.keyvault/vaults"] = "2023-07-01",
        ["microsoft.machinelearningservices/workspaces"] = "2024-10-01",
        ["microsoft.containerregistry/registries"] = "2023-11-01-preview",
        ["microsoft.app/containerapps"] = "2024-03-01",
        ["microsoft.app/managedenvironments"] = "2024-03-01",
        ["microsoft.communication/communicationservices"] = "2023-06-01-preview",
        ["microsoft.eventgrid/systemtopics"] = "2022-06-15",
        ["microsoft.network/networkwatchers"] = "2024-05-01",
        ["microsoft.devcenter/devcenters"] = "2024-10-01-preview",
        ["microsoft.devcenter/projects"] = "2024-10-01-preview",
        ["microsoft.insights/components"] = "2020-02-02-preview",
        ["microsoft.insights/actiongroups"] = "2023-01-01"
    };

    private static readonly Dictionary<string, string> _azurePauseActionTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["microsoft.dbformysql/flexibleservers"] = "stop",
        ["microsoft.containerinstance/containergroups"] = "stop",
        ["microsoft.web/sites"] = "stop"
    };

    private static readonly Dictionary<string, string> _azureResumeActionTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["microsoft.dbformysql/flexibleservers"] = "start",
        ["microsoft.containerinstance/containergroups"] = "start",
        ["microsoft.web/sites"] = "start"
    };

    private static readonly Dictionary<string, string> _azureRestartActionTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["microsoft.containerinstance/containergroups"] = "restart",
        ["microsoft.web/sites"] = "restart"
    };

    private sealed record ActionSpec(
        string Action,
        string Label,
        string Description,
        bool IsDestructive,
        string HttpMethod,
        string ApiVersion,
        string ActionPath);

    private sealed record TerraformCommandResult(string StandardOutput, string StandardError, int ExitCode);

    private sealed record AzureLongRunningOperationResult(
        string OperationState,
        int ResponseStatusCode,
        string? ResponseBody,
        string PollUri,
        bool TimedOut);

    private sealed class AzureTokenResponse
    {
        public string access_token { get; set; } = string.Empty;
        public string? refresh_token { get; set; }
        public int expires_in { get; set; }
    }
}
